version: "3.7"

services:
  web:
    image: "facial-key-backend" 
    command: sh -c "gunicorn FacialRecognitionBackendImp.wsgi:application --workers=5 --timeout=60000 --limit-request-line=100000 --bind 0.0.0.0:8000 --log-file /var/log/gunicorn.log"
    restart: unless-stopped
    volumes:
      - dataset:/usr/src/app/FacialRecognitionBackendImp/dataset/
    ports: 
      - 8000:8000
#   nginx:
#     hostname: ${DBS_ENV}-DOCK-NGINX
#     build: ./nginx
#     restart: unless-stopped
#     ports:
#       - ${SERVER_PORT}:80
#     volumes:
#       - staticfiles:/usr/src/app/staticfiles
#       - media:/usr/src/media:ro
volumes:
  dataset:
    name: "dataset"

